## Understanding Data Types in Python

In [ ]:
import numpy 
numpy.__version__

In [3]:
import numpy as np

In [5]:
np.abs

<ufunc 'absolute'>

In [7]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\elektra\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\elektra\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
 

In [9]:
/*C code */
int result = 0
for(int i =0; i<100; i++){
    result += i;
}

SyntaxError: Invalid star expression (3157574126.py, line 1)

In [11]:
result = 0
for i in range(100):
    result += i

In [13]:
x = 4
x = "four"

In [15]:
/* C code */ 
int x= 4;
x = "four"; //FAILS

SyntaxError: invalid syntax (491943047.py, line 1)

In [17]:
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};

SyntaxError: invalid syntax (2311031343.py, line 1)

In [21]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
type(L[0])

int

In [25]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [27]:
type(L2[0])

str

In [29]:
L3 = [True, "2", 3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [33]:
import array 
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
import numpy as np

In [37]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [41]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [43]:
np.array([range(i ,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [45]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [55]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [61]:
np.random.random((3,3))

array([[0.06613863, 0.57193796, 0.63518397],
       [0.63993185, 0.58911265, 0.53343076],
       [0.02821149, 0.28429712, 0.1374686 ]])

In [63]:
np.random.normal(0,1,(3,3))

array([[ 0.83143806,  0.1576275 , -2.79509019],
       [ 0.32475052, -0.5845611 ,  0.28727783],
       [-1.60653273,  0.68370454, -0.93968689]])

In [65]:
np.random.randint(0,10,(3,3))

array([[7, 1, 4],
       [6, 9, 8],
       [6, 2, 4]])

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.empty(3)

array([1., 1., 1.])

## Numpy Standar Dat type

In [72]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [74]:
np.zeros(10, dtype= np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## The basic of Numpy Arrays

In [79]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [81]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ",x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [83]:
print("dtype:",x3.dtype)

dtype: int32


In [85]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [87]:
x1

array([5, 0, 3, 3, 7, 9])

In [89]:
x1[0]

5

In [91]:
x1[4]

7

In [93]:
x1[-1]

9

In [95]:
x1[-2]

7

In [97]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [99]:
x2[0,0]

3

In [101]:
x2[2,0]

1

In [103]:
x2[2,-1]

7

In [110]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [112]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

## Array slicing

In [115]:
x[start:stop:step]

NameError: name 'start' is not defined

In [119]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
x[:5]

array([0, 1, 2, 3, 4])

In [123]:
x[5:]

array([5, 6, 7, 8, 9])

In [125]:
x[4:7]

array([4, 5, 6])

In [127]:
x[::2]

array([0, 2, 4, 6, 8])

In [129]:
x[1::2]

array([1, 3, 5, 7, 9])

In [131]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [139]:
x[5::-2]

array([5, 3, 1])

In [141]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [143]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [145]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [147]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [149]:
print(x2[:,0])

[12  7  1]


In [151]:
print(x2[0,:])

[12  5  2  4]


In [153]:
print(x2[0])

[12  5  2  4]


In [155]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [157]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [159]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [161]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [163]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [165]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [169]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [173]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [177]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [179]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [181]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [183]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [185]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [187]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [189]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [191]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [193]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [197]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [201]:
y = np.array([[99],
             [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [205]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [207]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [209]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [211]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on numpy arrays

In [214]:
import numpy as np 
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range (len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [216]:
big_array = np.random.randint(1,100, size = 1000000)
%timeit compute_reciprocals(bigarray)

NameError: name 'bigarray' is not defined

In [218]:
print(compute_reciprocals(values))
print(1.0 / values

SyntaxError: incomplete input (3900416982.py, line 2)

In [220]:
%timeit (1.0 / big_array)

2.88 ms ± 169 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [222]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [224]:
x = np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [228]:
x = np.arange(4)
print("x  =",x)
print("x+5 =",x+5)
print("x-5 = ", x-5)
print("x*2 = ", x*2)
print("x/2 = ", x/2)
print("x // 2 = ", x // 2)

x  = [0 1 2 3]
x+5 = [5 6 7 8]
x-5 =  [-5 -4 -3 -2]
x*2 =  [0 2 4 6]
x/2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [230]:
print("-x  =", -x)
print("x ** 2 =",x**2)
print("x%2 =",x%2)

-x  = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x%2 = [0 1 0 1]


In [232]:
-(0.5*x+1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [234]:
np.add(x,2)

array([2, 3, 4, 5])

In [236]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [238]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [240]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [242]:
x = np.array([3-4j, 4-3j, 2 + 0j, 0 +1j])
np.abs(x)

array([5., 5., 2., 1.])

## Trigonometric functions

In [245]:
theta = np.linspace(0,np.pi,3)

In [249]:
print("theta  =", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta)=", np.tan(theta))

theta  = [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [251]:
x = [-1,0,1]
print("x =",x)
print("arcsinn(x) =",np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x = [-1, 0, 1]
arcsinn(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


## Exponent and logarithms

In [254]:
x = [1,2,3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [260]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [262]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [264]:
from scipy import special

In [266]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [272]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [274]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)


[ 0. 10. 20. 30. 40.]


In [281]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [283]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [287]:
np.multiply.reduce(x)

120

In [289]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [292]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [294]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

## Min Max and Everything in Between